### ISSUE TITLE
Format for X/Y values for correct tree calculation

### ISSUE THREAD

**Issue by zachcp** [nextstrain/phyloTree#2]
HI @rneher and team phyloTree,

I am interested in making a pared down version of augur+phylo tree that lets you quickly generate interactive trees. I have in mind something similar-to but far simpler than Nextstrain. I am starting with a simple python script that will generate json consumable by phyloTree but I encounter some errors when loading it (see the screenshot below)  ( The code may look familiar  :) )

Almost certainly these are errors related to the X/Y values and/pr lack of branch length. Ideally I would like to be able to get the combination for rectangular/circular that you guys have so nicely put together. Do you have any recommendations for the most generic information that would allow you to use those layout algorithms?

A copy/paste of the json-generating code and json used below

Thanks,
zach cp

<img width="1317" alt="screen shot 2017-07-12 at 6 20 46 pm" src="https://user-images.githubusercontent.com/1260667/28142457-ef041f64-672e-11e7-9ea0-6ae221f8d7b5.png">

```
from io import StringIO
import pandas as pd
import numpy as np
from Bio import Phylo

def adorntree(tree, dataframe):
    """
    """
    dataframe = dataframe.set_index("node")
    nodevals = dataframe.to_dict("index")

    nodes  = set(nodevals.keys())
    rowprops = dataframe.columns

    nodenum = 0
    for treenode in tree.find_clades():

        if treenode.name in nodes:
            for attr in rowprops:
                treenode.__setattr__(attr, nodevals[treenode.name][attr])
        else:
            treenode.__setattr__("node", "NODE_{:06d}".format(nodenum))
        nodenum += 1
    return tree

def layout(tree):
    """Add clade, xvalue, yvalue, mutation and trunk attributes to all nodes in tree"""
    clade = 0
    yvalue = tree.count_terminals()
    for node in tree.find_clades(order="preorder"):
        node.clade = clade
        clade += 1
        node.xvalue = 0
        node.tvalue = 0
        if node.is_terminal():
            node.yvalue = yvalue
            yvalue -= 1
    for node in tree.get_nonterminals(order="postorder"):
        node.yvalue = np.mean([x.yvalue for x in node.clades])

    return tree


def tree_to_json(tree, exclude_attr = ['clades'], top_level_attr = ['clade','tvalue', 'xvalue', 'yvalue', 'strain', 'name']):
    tree_json = {}
    node = tree.root
    nodeprops = {key: value for key, value in node.__dict__.items()
                 if not key.startswith("__")
                 and key not in exclude_attr}
    tree_json["attr"] = {}
    if "name" in nodeprops.keys():
        tree_json["strain"] = nodeprops['name']
    if "id" in nodeprops.keys():
        tree_json["strain"] = nodeprops['id']
    if "node" in nodeprops.keys():
        tree_json["strain"] = nodeprops['node']

    for key, value in nodeprops.items():
        if value is not None:
            if key in top_level_attr:
                tree_json[key] = value
            else:
                tree_json["attr"][key] = value
    if node.clades:
        tree_json["children"] = []
        for ch in node.clades:
            tree_json["children"].append(tree_to_json(ch, exclude_attr))
    return tree_json

def write_json(data, file_name, indent=1):
    import json
    try:
        handle = open(file_name, 'w')
    except IOError:
        pass
    else:
        json.dump(data, handle, indent=indent)
        handle.close()

tree = Phylo.read(StringIO("(A, (B, C), (D, E))"), "newick")
tree = Phylo.read(StringIO("(B:6.0,(A:5.0,C:3.0,E:4.0):5.0,D:11.0);"), "newick")

Phylo.draw_ascii(tree)
nodes = pd.DataFrame({"node": ["A", "B", "C", "D", "E"],
                      "lat": [10,11,12,13,14],
                      "kind": ["AA", "BA", "CA", "DA", "EA"]})

tree2 = adorntree(tree, nodes)
tree3 = layout(tree2)
tree4 = tree_to_json(tree=tree3)
write_json(tree4, "/Users/zach/Desktop/phyloTree/data/testdata.json")
```

```
{
 "attr": {
  "node": "NODE_000000"
 },
 "strain": "NODE_000000",
 "clade": 0,
 "xvalue": 0,
 "tvalue": 0,
 "yvalue": 3.0,
 "children": [
  {
   "attr": {
    "branch_length": 6.0,
    "kind": "BA",
    "lat": 11
   },
   "strain": "B",
   "name": "B",
   "clade": 1,
   "xvalue": 0,
   "tvalue": 0,
   "yvalue": 5
  },
  {
   "attr": {
    "branch_length": 5.0,
    "node": "NODE_000002"
   },
   "strain": "NODE_000002",
   "clade": 2,
   "xvalue": 0,
   "tvalue": 0,
   "yvalue": 3.0,
   "children": [
    {
     "attr": {
      "branch_length": 5.0,
      "kind": "AA",
      "lat": 10
     },
     "strain": "A",
     "name": "A",
     "clade": 3,
     "xvalue": 0,
     "tvalue": 0,
     "yvalue": 4
    },
    {
     "attr": {
      "branch_length": 3.0,
      "kind": "CA",
      "lat": 12
     },
     "strain": "C",
     "name": "C",
     "clade": 4,
     "xvalue": 0,
     "tvalue": 0,
     "yvalue": 3
    },
    {
     "attr": {
      "branch_length": 4.0,
      "kind": "EA",
      "lat": 14
     },
     "strain": "E",
     "name": "E",
     "clade": 5,
     "xvalue": 0,
     "tvalue": 0,
     "yvalue": 2
    }
   ]
  },
  {
   "attr": {
    "branch_length": 11.0,
    "kind": "DA",
    "lat": 13
   },
   "strain": "D",
   "name": "D",
   "clade": 6,
   "xvalue": 0,
   "tvalue": 0,
   "yvalue": 1
  }
 ]
}
```

**Comment by rneher** [comment]
To clarify. the phyloTree repo is my attempt to make the treeviewer available outside of nextstrain and separate code and data a bit. nextstrain uses a related version of this where everything is one big object (https://github.com/nextstrain/auspice/blob/master/src/util/phyloTree.js). not sure which one is the best way forward (cc @jameshadfield). 

your problem here is most like the x and ys. You can remove `xvalue` and `yvalue`. Those aren't used. But move the `branch_length` outside of the attribute object. The new logic is such that you can use various attributes for branch length (like divergence `div`, time `numdate`, or whatever), but if these are absent `attr.div` is constructed from `node.branch_length`.
https://github.com/nextstrain/phyloTree/blob/master/src/phyloTree.js#L44

**Comment by zachcp** [comment]
thanks @rneher and @jameshadfield ,

A simple treeviewer would be fantastic. For some internal applications I've been using Phylocanvas (which I think james is familiar with) but phylotree would be far superior, especially if it had the following combination of winning features:

1. customizable colors of tips
2. tooltips for storing node-info
3. changing radial/rectangular on the fly.
4. easy-to-serialize-to json format to allow generic data.

Of course these are already in Nextstrain!

I will change the branchlengths and try my data again.

Thanks,
zcp

**Comment by rneher** [comment]
yes, all of this is basically in place. but I don't know enough about proper javascript programming to make this into a reusable piece of software...

**Comment by zachcp** [comment]
for really custom stuff I think you will always need to program JS.  My hope/goal is to package this up into something like an HTMLWidget for R  (or a Dash widget for python) where you get a tree with a limited number of common customization but its trivially easy to create/use with your own data.   To get there form here you just need to be able to assign nodes with arbitrary data that can be exposed to coloring api and/or the tooltips. The tooltip part would be tough and  to make it work really well would be tricky (see Rstudio's [leaflet wrapper](https://rstudio.github.io/leaflet/).) 

Not sure if the best thing is to simply make a generic JS package that could be consumed for custom apps or what but I appreciate your efforts.
